work_dir: ./work_dir/mnist_2
#weights: ./work_dir/skating/CW/runs-219-4380.pt

# feeder
feeder: feeder.mnist.Feeder
train_feeder_args:
  debug: False
  state: 0

test_feeder_args:
  debug: False
  state: 1

# model
model: model.net.Model
model_args:
  in_chans: 1

#training
device: [0]
batch_size: 16
test_batch_size: 16

#optim
base_lr: 0.1
step: [150, 225]
num_epoch: 10
lr_decay_rate: 1
warm_up_epoch: 1
save_epoch: 0
weight_decay: 0.000001
momentum: 0
seed: 42
grad_norm: True
clip: 1000

compile: True
#compile: default, reduce-overhead or max-autotune
compile_mode: default
AMP: False
AMP_scaler: False
