work_dir: ./work_dir/mnist
#weights: ./work_dir/skating/CW/runs-219-4380.pt

# feeder
feeder: feeder.mnist.Feeder
train_feeder_args:
  debug: False
  state: 0

test_feeder_args:
  debug: False
  state: 1

# model
model: model.net.LeNet
model_args:
  kernel_size: 5
  padding: 2
  stride: 2

#training
device: [0]
batch_size: 16
test_batch_size: 16

#optim
base_lr: 0.1
step: [150, 225]
num_epoch: 20
lr_decay_rate: 0.1
warm_up_epoch: 5
save_epoch: 5

seed: 5
